/**
 * Demo Data Service
 * Provides mock data for demo mode
 */

import type {
  GetDashboardDataQuery,
  GetDockerContainersQuery,
  GetVmsQuery,
} from '@/src/graphql/generated';

export const DEMO_DASHBOARD_DATA: GetDashboardDataQuery = {
  __typename: 'Query',
  array: {
    __typename: 'UnraidArray',
    id: 'demo:array:1',
    state: 'STARTED',
    capacity: {
      __typename: 'ArrayCapacity',
      kilobytes: {
        __typename: 'Capacity',
        // Values in KB: 24 TB = ~25.77 billion KB, 8.8 TB = ~9.45 billion KB, 15.2 TB = ~16.32 billion KB
        free: '16320875725',
        used: '9448928051',
        total: '25769803776',
      },
      disks: {
        __typename: 'Capacity',
        free: '3',
        used: '5',
        total: '8',
      },
    },
    parityCheckStatus: {
      __typename: 'ParityCheck',
      date: new Date('2024-11-01T03:00:00Z').toISOString() as any,
      duration: 28800,
      speed: '145 MB/s',
      status: 'COMPLETED',
      errors: 0,
      progress: 100,
      correcting: false,
      paused: false,
      running: false,
    },
    disks: [
      {
        __typename: 'ArrayDisk',
        id: 'demo:disk:1',
        idx: 1,
        name: 'disk1',
        device: 'sdb',
        size: '4000000000',
        status: 'DISK_OK',
        rotational: true,
        temp: 35,
        numReads: '1234567890',
        numWrites: '987654321',
        numErrors: '0',
        fsSize: '3900000000',
        fsFree: '1500000000',
        fsUsed: '2400000000',
        exportable: true,
        type: 'DATA',
        warning: 10,
        critical: 5,
        fsType: 'xfs',
        comment: 'Primary data disk',
        format: 'MBR: 4KiB-aligned',
        transport: 'sata',
        color: 'GREEN_ON',
        isSpinning: true,
      },
      {
        __typename: 'ArrayDisk',
        id: 'demo:disk:2',
        idx: 2,
        name: 'disk2',
        device: 'sdc',
        size: '4000000000',
        status: 'DISK_OK',
        rotational: true,
        temp: 33,
        numReads: '987654321',
        numWrites: '1234567890',
        numErrors: '0',
        fsSize: '3900000000',
        fsFree: '2000000000',
        fsUsed: '1900000000',
        exportable: true,
        type: 'DATA',
        warning: 10,
        critical: 5,
        fsType: 'xfs',
        comment: 'Secondary data disk',
        format: 'MBR: 4KiB-aligned',
        transport: 'sata',
        color: 'GREEN_ON',
        isSpinning: true,
      },
      {
        __typename: 'ArrayDisk',
        id: 'demo:disk:3',
        idx: 3,
        name: 'disk3',
        device: 'sdd',
        size: '8000000000',
        status: 'DISK_OK',
        rotational: true,
        temp: 38,
        numReads: '2345678901',
        numWrites: '1876543210',
        numErrors: '0',
        fsSize: '7800000000',
        fsFree: '3000000000',
        fsUsed: '4800000000',
        exportable: true,
        type: 'DATA',
        warning: 10,
        critical: 5,
        fsType: 'xfs',
        comment: 'Large capacity disk',
        format: 'MBR: 4KiB-aligned',
        transport: 'sata',
        color: 'GREEN_ON',
        isSpinning: true,
      },
    ],
    parities: [
      {
        __typename: 'ArrayDisk',
        id: 'demo:parity:1',
        idx: 0,
        name: 'parity',
        device: 'sda',
        size: '8000000000',
        status: 'DISK_OK',
        rotational: true,
        temp: 36,
        numReads: '3456789012',
        numWrites: '2987654321',
        numErrors: '0',
        fsSize: null,
        fsFree: null,
        fsUsed: null,
        exportable: false,
        type: 'PARITY',
        warning: 10,
        critical: 5,
        fsType: null,
        comment: 'Parity protection',
        format: 'MBR: 4KiB-aligned',
        transport: 'sata',
        color: 'BLUE_ON',
        isSpinning: true,
      },
    ],
    caches: [
      {
        __typename: 'ArrayDisk',
        id: 'demo:cache:1',
        idx: 30,
        name: 'cache',
        device: 'nvme0n1',
        size: '1000000000',
        status: 'DISK_OK',
        rotational: false,
        temp: 42,
        numReads: '9876543210',
        numWrites: '8765432109',
        numErrors: '0',
        fsSize: '950000000',
        fsFree: '450000000',
        fsUsed: '500000000',
        exportable: true,
        type: 'CACHE',
        warning: 10,
        critical: 5,
        fsType: 'btrfs',
        comment: 'NVMe cache drive',
        format: 'GPT',
        transport: 'nvme',
        color: 'GREEN_ON',
        isSpinning: false,
      },
    ],
    boot: {
      __typename: 'ArrayDisk',
      id: 'demo:boot:1',
      idx: 54,
      name: 'Flash',
      device: 'sde',
      size: '67500000',
      status: 'DISK_OK',
      rotational: false,
      temp: null,
      numReads: '123456',
      numWrites: '654321',
      numErrors: '0',
      fsSize: '67500000',
      fsFree: '66500000',
      fsUsed: '1000000',
      exportable: false,
      type: 'FLASH',
      warning: 10,
      critical: 5,
      fsType: 'vfat',
      comment: null,
      format: 'MBR',
      transport: 'usb',
      color: null,
      isSpinning: false,
    },
  },
  shares: [
    {
      __typename: 'Share',
      id: 'demo:share:1',
      name: 'Media',
      free: '5000000000',
      used: '3000000000',
      size: '8000000000',
      include: ['disk1', 'disk2', 'disk3'],
      exclude: [],
      cache: true,
      nameOrig: 'Media',
      comment: 'Movies, TV Shows, and Music',
      allocator: 'highwater',
      splitLevel: 'auto',
      floor: '0',
      cow: 'auto',
      color: null,
      luksStatus: null,
    },
    {
      __typename: 'Share',
      id: 'demo:share:2',
      name: 'Documents',
      free: '800000000',
      used: '200000000',
      size: '1000000000',
      include: ['disk1', 'disk2'],
      exclude: [],
      cache: true,
      nameOrig: 'Documents',
      comment: 'Personal and work documents',
      allocator: 'highwater',
      splitLevel: 'auto',
      floor: '0',
      cow: 'auto',
      color: null,
      luksStatus: null,
    },
    {
      __typename: 'Share',
      id: 'demo:share:3',
      name: 'Backups',
      free: '2000000000',
      used: '3000000000',
      size: '5000000000',
      include: ['disk2', 'disk3'],
      exclude: [],
      cache: false,
      nameOrig: 'Backups',
      comment: 'System and data backups',
      allocator: 'highwater',
      splitLevel: 'auto',
      floor: '0',
      cow: 'auto',
      color: null,
      luksStatus: null,
    },
  ],
  info: {
    __typename: 'Info',
    id: 'demo:info:1',
    time: new Date().toISOString() as any,
    baseboard: {
      __typename: 'InfoBaseboard',
      id: 'demo:baseboard:1',
      manufacturer: 'ASRock',
      model: 'X570 Taichi',
      version: '1.0',
      serial: 'DEMO123456789',
      assetTag: null,
      memMax: 137438953472,
      memSlots: 4,
    },
    cpu: {
      __typename: 'InfoCpu',
      id: 'demo:cpu:1',
      manufacturer: 'AMD',
      brand: 'AMD Ryzen 9 5950X',
      vendor: 'AuthenticAMD',
      family: '19',
      model: '33',
      stepping: 0,
      revision: null,
      voltage: '1.35V',
      speed: 3.4,
      speedmin: 2.2,
      speedmax: 4.9,
      threads: 32,
      cores: 16,
      processors: 1,
      socket: 'AM4',
      cache: {
        l1d: 524288,
        l1i: 524288,
        l2: 8388608,
        l3: 67108864,
      },
      flags: [
        'fpu',
        'vme',
        'de',
        'pse',
        'tsc',
        'msr',
        'pae',
        'mce',
        'cx8',
        'apic',
        'sep',
        'mtrr',
        'pge',
        'mca',
        'cmov',
        'pat',
        'pse36',
        'clflush',
        'mmx',
        'fxsr',
        'sse',
        'sse2',
        'ht',
        'syscall',
        'nx',
        'mmxext',
        'fxsr_opt',
        'pdpe1gb',
        'rdtscp',
        'lm',
        'constant_tsc',
        'rep_good',
        'nopl',
        'nonstop_tsc',
        'cpuid',
        'extd_apicid',
        'aperfmperf',
        'pni',
        'pclmulqdq',
        'monitor',
        'ssse3',
        'fma',
        'cx16',
        'sse4_1',
        'sse4_2',
        'movbe',
        'popcnt',
        'aes',
        'xsave',
        'avx',
        'f16c',
        'rdrand',
        'lahf_lm',
        'cmp_legacy',
        'svm',
        'extapic',
        'cr8_legacy',
        'abm',
        'sse4a',
        'misalignsse',
        '3dnowprefetch',
        'osvw',
        'ibs',
        'skinit',
        'wdt',
        'tce',
        'topoext',
        'perfctr_core',
        'perfctr_nb',
        'bpext',
        'perfctr_llc',
        'mwaitx',
        'cpb',
        'cat_l3',
        'cdp_l3',
        'hw_pstate',
        'ssbd',
        'mba',
        'ibrs',
        'ibpb',
        'stibp',
        'vmmcall',
        'fsgsbase',
        'bmi1',
        'avx2',
        'smep',
        'bmi2',
        'erms',
        'invpcid',
        'cqm',
        'rdt_a',
        'rdseed',
        'adx',
        'smap',
        'clflushopt',
        'clwb',
        'sha_ni',
        'xsaveopt',
        'xsavec',
        'xgetbv1',
        'xsaves',
        'cqm_llc',
        'cqm_occup_llc',
        'cqm_mbm_total',
        'cqm_mbm_local',
        'clzero',
        'irperf',
        'xsaveerptr',
        'rdpru',
        'wbnoinvd',
        'arat',
        'tsc_scale',
        'vmcb_clean',
        'flushbyasid',
        'decodeassists',
        'pausefilter',
        'pfthreshold',
        'avic',
        'v_vmsave_vmload',
        'vgif',
        'v_spec_ctrl',
        'umip',
        'pku',
        'ospke',
        'vaes',
        'vpclmulqdq',
        'rdpid',
        'overflow_recov',
        'succor',
        'smca',
        'fsrm',
      ],
    },
    devices: {
      __typename: 'InfoDevices',
      id: 'demo:devices:1',
      gpu: [
        {
          __typename: 'InfoGpu',
          id: 'demo:gpu:1',
          type: 'NVIDIA',
          typeid: '10de',
          blacklisted: false,
          class: 'VGA compatible controller',
          productid: '2204',
          vendorname: 'NVIDIA Corporation',
        },
      ],
      network: [
        {
          __typename: 'InfoNetwork',
          id: 'demo:network:1',
          iface: 'eth0',
          model: 'Intel I211 Gigabit Network Connection',
          vendor: 'Intel Corporation',
          mac: '00:11:22:33:44:55',
          virtual: false,
          speed: '1000 Mbps',
          dhcp: true,
        },
        {
          __typename: 'InfoNetwork',
          id: 'demo:network:2',
          iface: 'eth1',
          model: 'Intel I211 Gigabit Network Connection',
          vendor: 'Intel Corporation',
          mac: '00:11:22:33:44:66',
          virtual: false,
          speed: '1000 Mbps',
          dhcp: false,
        },
      ],
      pci: [],
      usb: [
        {
          __typename: 'InfoUsb',
          id: 'demo:usb:1',
          name: 'USB Flash Drive',
          bus: '1',
          device: '2',
        },
      ],
    },
    display: {
      __typename: 'InfoDisplay',
      id: 'demo:display:1',
      case: {
        __typename: 'InfoDisplayCase',
        id: 'demo:case:1',
        url: '',
        icon: 'default',
        error: '',
        base64: '',
      },
      theme: 'black',
      unit: 'CELSIUS',
      scale: true,
      tabs: true,
      resize: true,
      wwn: false,
      total: true,
      usage: true,
      text: true,
      warning: 40,
      critical: 50,
      hot: 60,
      max: 70,
      locale: 'en-US',
    },
    machineId: 'demo-machine-id-12345',
    memory: {
      __typename: 'InfoMemory',
      id: 'demo:memory:1',
      layout: [
        {
          __typename: 'MemoryLayout',
          id: 'demo:memory:layout:1',
          size: '34359738368',
          bank: 'BANK 0',
          type: 'DDR4',
          clockSpeed: 3600,
          partNum: 'CMK32GX4M2D3600C18',
          serialNum: 'DEMO001',
          manufacturer: 'Corsair',
          formFactor: 'DIMM',
          voltageConfigured: 1350,
          voltageMin: 1200,
          voltageMax: 1500,
        },
        {
          __typename: 'MemoryLayout',
          id: 'demo:memory:layout:2',
          size: '34359738368',
          bank: 'BANK 1',
          type: 'DDR4',
          clockSpeed: 3600,
          partNum: 'CMK32GX4M2D3600C18',
          serialNum: 'DEMO002',
          manufacturer: 'Corsair',
          formFactor: 'DIMM',
          voltageConfigured: 1350,
          voltageMin: 1200,
          voltageMax: 1500,
        },
      ],
    },
    os: {
      __typename: 'InfoOs',
      id: 'demo:os:1',
      platform: 'linux',
      distro: 'Slackware',
      release: '15.0',
      codename: null,
      kernel: '6.1.38-Unraid',
      arch: 'x86_64',
      hostname: 'Demo-Server',
      fqdn: 'demo-server.local',
      build: null,
      servicepack: null,
      uptime: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      logofile: 'slackware',
      serial: null,
      uefi: true,
    },
    system: {
      __typename: 'InfoSystem',
      id: 'demo:system:1',
      manufacturer: 'Custom Build',
      model: 'Unraid Server',
      version: '1.0',
      serial: 'DEMO-SYSTEM-001',
      uuid: '12345678-1234-1234-1234-123456789012',
      sku: null,
      virtual: false,
    },
    versions: {
      __typename: 'InfoVersions',
      id: 'demo:versions:1',
      core: {
        __typename: 'CoreVersions',
        unraid: '6.12.6',
        api: '2.0.0',
        kernel: '6.1.38',
      },
      packages: {
        __typename: 'PackageVersions',
        openssl: '3.0.11',
        node: '20.10.0',
        npm: '10.2.3',
        pm2: '5.3.0',
        git: '2.43.0',
        nginx: '1.24.0',
        php: '8.2.13',
        docker: '24.0.7',
      },
    },
  },
  metrics: {
    __typename: 'Metrics',
    id: 'demo:metrics:1',
    cpu: {
      __typename: 'CpuUtilization',
      id: 'demo:cpu:util:1',
      percentTotal: 25.5,
      cpus: Array.from({ length: 32 }, (_, i) => ({
        __typename: 'CpuLoad' as const,
        percentTotal: Math.random() * 40 + 10,
        percentUser: Math.random() * 20 + 5,
        percentSystem: Math.random() * 10 + 2,
        percentNice: 0,
        percentIdle: Math.random() * 60 + 40,
        percentIrq: Math.random() * 2,
        percentGuest: 0,
        percentSteal: 0,
      })),
    },
    memory: {
      __typename: 'MemoryUtilization',
      id: 'demo:memory:util:1',
      total: '68719476736',
      used: '34359738368',
      free: '34359738368',
      available: '40000000000',
      active: '30000000000',
      buffcache: '4359738368',
      percentTotal: 50.0,
      swapTotal: '8589934592',
      swapUsed: '0',
      swapFree: '8589934592',
      percentSwapTotal: 0,
    },
  },
  vars: {
    __typename: 'Vars',
    id: 'demo:vars:1',
    version: '6.12.6',
    maxArraysz: 28,
    maxCachesz: 24,
    name: 'Demo-Server',
    timeZone: 'America/New_York',
    comment: 'Demo Unraid Server for Testing',
    security: 'public',
    workgroup: 'WORKGROUP',
    domain: null,
    domainShort: null,
    hideDotFiles: true,
    localMaster: true,
    enableFruit: 'yes',
    useNtp: true,
    ntpServer1: 'pool.ntp.org',
    ntpServer2: 'time.google.com',
    ntpServer3: 'time.cloudflare.com',
    ntpServer4: null,
    domainLogin: null,
    sysModel: 'Custom',
    sysArraySlots: 28,
    sysCacheSlots: 24,
    sysFlashSlots: 1,
    useSsl: true,
    port: 80,
    portssl: 443,
    localTld: 'local',
    bindMgt: true,
    useTelnet: false,
    porttelnet: 23,
    useSsh: true,
    portssh: 22,
    startPage: 'Main',
    startArray: true,
    spindownDelay: '30',
    queueDepth: '32',
    spinupGroups: false,
    defaultFormat: 'xfs',
    defaultFsType: 'xfs',
    shutdownTimeout: 60,
    luksKeyfile: null,
    pollAttributes: 'auto',
    pollAttributesDefault: 'auto',
    pollAttributesStatus: 'enabled',
    nrRequests: 128,
    nrRequestsDefault: 128,
    nrRequestsStatus: 'default',
    mdNumStripes: 4096,
    mdNumStripesDefault: 4096,
    mdNumStripesStatus: 'default',
    mdSyncWindow: 4096,
    mdSyncWindowDefault: 4096,
    mdSyncWindowStatus: 'default',
    mdSyncThresh: 2048,
    mdSyncThreshDefault: 2048,
    mdSyncThreshStatus: 'default',
    mdWriteMethod: 1,
    mdWriteMethodDefault: 'auto',
    mdWriteMethodStatus: 'default',
    shareDisk: 'enabled',
    shareUser: 'enabled',
    shareUserInclude: null,
    shareUserExclude: null,
    shareSmbEnabled: true,
    shareNfsEnabled: true,
    shareAfpEnabled: false,
    shareInitialOwner: 'nobody',
    shareInitialGroup: 'users',
    shareCacheEnabled: true,
    shareCacheFloor: '0',
    shareMoverSchedule: '0 3 * * *',
    shareMoverLogging: true,
    fuseRemember: '1',
    fuseRememberDefault: '1',
    fuseRememberStatus: 'default',
    fuseDirectio: 'off',
    fuseDirectioDefault: 'off',
    fuseDirectioStatus: 'default',
    shareAvahiEnabled: true,
    shareAvahiSmbName: 'Demo Server',
    shareAvahiSmbModel: 'Xserve',
    shareAvahiAfpName: null,
    shareAvahiAfpModel: null,
    safeMode: false,
    startMode: 'normal',
    configValid: true,
    configError: null,
    joinStatus: null,
    deviceCount: 8,
    flashGuid: '12345678-1234-1234-1234-123456789012',
    flashProduct: 'USB Flash Drive',
    flashVendor: 'SanDisk',
    regCheck: 'valid',
    regFile: '/boot/config/Pro.key',
    regGuid: '12345678-1234-1234-1234-123456789012',
    regTy: 'PRO',
    regState: 'PRO',
    regTo: 'Demo User',
    regTm: '2024-01-01',
    regTm2: null,
    regGen: '1',
    sbName: null,
    sbVersion: null,
    sbUpdated: null,
    sbEvents: 0,
    sbState: null,
    sbClean: true,
    sbSynced: 0,
    sbSyncErrs: 0,
    sbSynced2: 0,
    sbSyncExit: null,
    sbNumDisks: 0,
    mdColor: 'green',
    mdNumDisks: 8,
    mdNumDisabled: 0,
    mdNumInvalid: 0,
    mdNumMissing: 0,
    mdNumNew: 0,
    mdNumErased: 0,
    mdResync: 0,
    mdResyncCorr: '0',
    mdResyncPos: '0',
    mdResyncDb: '0',
    mdResyncDt: '0',
    mdResyncAction: null,
    mdResyncSize: 0,
    mdState: 'STARTED',
    mdVersion: '1.2',
    cacheNumDevices: 1,
    cacheSbNumDisks: 1,
    fsState: 'Started',
    fsProgress: null,
    fsCopyPrcnt: 0,
    fsNumMounted: 8,
    fsNumUnmountable: 0,
    fsUnmountableMask: null,
    shareCount: 3,
    shareSmbCount: 3,
    shareNfsCount: 2,
    shareAfpCount: 0,
    shareMoverActive: false,
    csrfToken: 'demo-csrf-token',
  },
  vms: {
    __typename: 'Vms',
    id: 'demo:vms:1',
    domains: [
      {
        __typename: 'VmDomain',
        id: 'demo:vm:1',
        name: 'Windows 10 Pro',
        state: 'RUNNING',
        uuid: 'vm-uuid-1',
      },
      {
        __typename: 'VmDomain',
        id: 'demo:vm:2',
        name: 'Ubuntu Server',
        state: 'SHUTOFF',
        uuid: 'vm-uuid-2',
      },
      {
        __typename: 'VmDomain',
        id: 'demo:vm:3',
        name: 'macOS Monterey',
        state: 'PAUSED',
        uuid: 'vm-uuid-3',
      },
    ],
    domain: [],
  },
};

export const DEMO_DOCKER_DATA: GetDockerContainersQuery = {
  __typename: 'Query',
  docker: {
    __typename: 'Docker',
    id: 'demo:docker:1',
    containers: [
      {
        __typename: 'DockerContainer',
        id: 'demo:container:1',
        names: ['/plex'],
        image: 'plexinc/pms-docker:latest',
        imageId: 'sha256:abc123def456',
        command: '/init',
        created: Math.floor(Date.now() / 1000) - 86400 * 30,
        ports: [
          {
            __typename: 'ContainerPort',
            ip: '0.0.0.0',
            privatePort: 32400,
            publicPort: 32400,
            type: 'TCP',
          },
        ],
        sizeRootFs: '5368709120',
        labels: {
          'net.unraid.docker.managed': 'dockerman',
          'net.unraid.docker.icon': 'https://raw.githubusercontent.com/plexinc/pms-docker/master/img/plex-icon.png',
        },
        state: 'RUNNING',
        status: 'Up 7 days',
        hostConfig: {
          __typename: 'ContainerHostConfig',
          networkMode: 'bridge',
        },
        networkSettings: {},
        mounts: [],
        autoStart: true,
      },
      {
        __typename: 'DockerContainer',
        id: 'demo:container:2',
        names: ['/sonarr'],
        image: 'linuxserver/sonarr:latest',
        imageId: 'sha256:def456ghi789',
        command: '/init',
        created: Math.floor(Date.now() / 1000) - 86400 * 15,
        ports: [
          {
            __typename: 'ContainerPort',
            ip: '0.0.0.0',
            privatePort: 8989,
            publicPort: 8989,
            type: 'TCP',
          },
        ],
        sizeRootFs: '1073741824',
        labels: {
          'net.unraid.docker.managed': 'dockerman',
          'net.unraid.docker.icon': 'https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sonarr-icon.png',
        },
        state: 'RUNNING',
        status: 'Up 3 days',
        hostConfig: {
          __typename: 'ContainerHostConfig',
          networkMode: 'bridge',
        },
        networkSettings: {},
        mounts: [],
        autoStart: true,
      },
      {
        __typename: 'DockerContainer',
        id: 'demo:container:3',
        names: ['/radarr'],
        image: 'linuxserver/radarr:latest',
        imageId: 'sha256:ghi789jkl012',
        command: '/init',
        created: Math.floor(Date.now() / 1000) - 86400 * 15,
        ports: [
          {
            __typename: 'ContainerPort',
            ip: '0.0.0.0',
            privatePort: 7878,
            publicPort: 7878,
            type: 'TCP',
          },
        ],
        sizeRootFs: '1073741824',
        labels: {
          'net.unraid.docker.managed': 'dockerman',
          'net.unraid.docker.icon': 'https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/radarr-icon.png',
        },
        state: 'RUNNING',
        status: 'Up 3 days',
        hostConfig: {
          __typename: 'ContainerHostConfig',
          networkMode: 'bridge',
        },
        networkSettings: {},
        mounts: [],
        autoStart: true,
      },
      {
        __typename: 'DockerContainer',
        id: 'demo:container:4',
        names: ['/nginx'],
        image: 'nginx:latest',
        imageId: 'sha256:jkl012mno345',
        command: 'nginx -g daemon off;',
        created: Math.floor(Date.now() / 1000) - 86400 * 60,
        ports: [
          {
            __typename: 'ContainerPort',
            ip: '0.0.0.0',
            privatePort: 80,
            publicPort: 8080,
            type: 'TCP',
          },
        ],
        sizeRootFs: '536870912',
        labels: {},
        state: 'EXITED',
        status: 'Exited (0) 2 hours ago',
        hostConfig: {
          __typename: 'ContainerHostConfig',
          networkMode: 'bridge',
        },
        networkSettings: {},
        mounts: [],
        autoStart: false,
      },
      {
        __typename: 'DockerContainer',
        id: 'demo:container:5',
        names: ['/nextcloud'],
        image: 'nextcloud:latest',
        imageId: 'sha256:mno345pqr678',
        command: '/entrypoint.sh apache2-foreground',
        created: Math.floor(Date.now() / 1000) - 86400 * 45,
        ports: [
          {
            __typename: 'ContainerPort',
            ip: '0.0.0.0',
            privatePort: 80,
            publicPort: 8081,
            type: 'TCP',
          },
        ],
        sizeRootFs: '2147483648',
        labels: {
          'net.unraid.docker.managed': 'dockerman',
          'net.unraid.docker.icon': 'https://raw.githubusercontent.com/nextcloud/docker/master/.examples/docker-compose/insecure/mariadb/fpm/web/icon.png',
        },
        state: 'RUNNING',
        status: 'Up 10 days',
        hostConfig: {
          __typename: 'ContainerHostConfig',
          networkMode: 'bridge',
        },
        networkSettings: {},
        mounts: [],
        autoStart: true,
      },
    ],
  },
};

export const DEMO_VMS_DATA: GetVmsQuery = {
  __typename: 'Query',
  vms: {
    __typename: 'Vms',
    id: 'demo:vms:1',
    domains: [
      {
        __typename: 'VmDomain',
        id: 'demo:vm:1',
        name: 'Windows 10 Pro',
        state: 'RUNNING',
        uuid: 'vm-uuid-1',
      },
      {
        __typename: 'VmDomain',
        id: 'demo:vm:2',
        name: 'Ubuntu Server',
        state: 'SHUTOFF',
        uuid: 'vm-uuid-2',
      },
      {
        __typename: 'VmDomain',
        id: 'demo:vm:3',
        name: 'macOS Monterey',
        state: 'PAUSED',
        uuid: 'vm-uuid-3',
      },
    ],
  },
};

type DemoNotificationCounts = {
  info: number;
  warning: number;
  alert: number;
  total: number;
};

type DemoNotificationItem = {
  id: string;
  title: string;
  subject: string;
  description: string;
  importance: 'ALERT' | 'WARNING' | 'INFO';
  type: 'UNREAD' | 'ARCHIVE';
  link?: string | null;
  timestamp?: string | null;
  formattedTimestamp?: string | null;
};

type DemoNotificationsData = {
  notifications: {
    overview: {
      unread: DemoNotificationCounts;
      archive: DemoNotificationCounts;
    };
    list: DemoNotificationItem[];
  };
};

export const DEMO_NOTIFICATIONS_DATA: DemoNotificationsData = {
  notifications: {
    overview: {
      unread: {
        info: 3,
        warning: 2,
        alert: 1,
        total: 6,
      },
      archive: {
        info: 4,
        warning: 1,
        alert: 0,
        total: 5,
      },
    },
    list: [
      {
        id: 'demo:notification:1',
        title: 'Parity check completed',
        subject: 'Array status',
        description: 'Last scheduled parity check completed successfully with zero errors detected.',
        importance: 'INFO',
        type: 'UNREAD',
        formattedTimestamp: '5 minutes ago',
        timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      },
      {
        id: 'demo:notification:2',
        title: 'Docker container update available',
        subject: 'Plex Media Server',
        description: 'A new version of the Plex container is available. Review the changelog before updating.',
        importance: 'WARNING',
        type: 'UNREAD',
        formattedTimestamp: '14 minutes ago',
        timestamp: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
        link: 'https://support.plex.tv/articles/201904005-update-plex-media-server/',
      },
      {
        id: 'demo:notification:3',
        title: 'Array disk temperature warning',
        subject: 'Disk 3 (sdd)',
        description: 'Disk temperature reached 49°C which exceeds the configured warning threshold.',
        importance: 'WARNING',
        type: 'UNREAD',
        formattedTimestamp: '37 minutes ago',
        timestamp: new Date(Date.now() - 37 * 60 * 1000).toISOString(),
      },
      {
        id: 'demo:notification:4',
        title: 'Critical SMART error detected',
        subject: 'Disk 5 (sdf)',
        description: 'SMART attribute 197 (Current Pending Sector Count) exceeded the critical threshold.',
        importance: 'ALERT',
        type: 'UNREAD',
        formattedTimestamp: '1 hour ago',
        timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
        link: 'https://wiki.unraid.net/Manual/Storage_Management#SMART_attributes',
      },
      {
        id: 'demo:notification:5',
        title: 'Flash backup completed',
        subject: 'Backup to Dropbox',
        description: 'Flash drive backup to Dropbox finished successfully.',
        importance: 'INFO',
        type: 'UNREAD',
        formattedTimestamp: '2 hours ago',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'demo:notification:6',
        title: 'System update available',
        subject: 'Unraid OS 6.12.5',
        description: 'A new Unraid OS release is available with bug fixes and security updates.',
        importance: 'INFO',
        type: 'UNREAD',
        formattedTimestamp: '3 hours ago',
        timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        link: 'https://wiki.unraid.net/Manual/Release_Notes',
      },
      {
        id: 'demo:notification:7',
        title: 'Docker update applied',
        subject: 'Nextcloud',
        description: 'Docker container was updated to version 27.1.2. Restart required to apply changes.',
        importance: 'INFO',
        type: 'ARCHIVE',
        formattedTimestamp: 'Yesterday',
        timestamp: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'demo:notification:8',
        title: 'VM started',
        subject: 'Windows 11 Workstation',
        description: 'Virtual machine was started by user admin from the dashboard.',
        importance: 'INFO',
        type: 'ARCHIVE',
        formattedTimestamp: 'Yesterday',
        timestamp: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'demo:notification:9',
        title: 'Mover finished transferring cache contents',
        subject: 'Cache to array',
        description: 'Scheduled mover operation completed successfully.',
        importance: 'INFO',
        type: 'ARCHIVE',
        formattedTimestamp: '2 days ago',
        timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'demo:notification:10',
        title: 'UPS on battery',
        subject: 'APC Back-UPS Pro',
        description: 'Power outage detected. Server running on battery backup. Estimated runtime 58 minutes.',
        importance: 'WARNING',
        type: 'ARCHIVE',
        formattedTimestamp: '2 days ago',
        timestamp: new Date(Date.now() - 50 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'demo:notification:11',
        title: 'Network link restored',
        subject: 'eth0',
        description: 'Network connectivity restored after brief interruption.',
        importance: 'INFO',
        type: 'ARCHIVE',
        formattedTimestamp: '3 days ago',
        timestamp: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
      },
    ],
  },
};

export class DemoDataService {
  static isDemoMode(): boolean {
    // Check if we're in demo mode
    return global.__DEMO_MODE__ === true;
  }

  static enableDemoMode(): void {
    global.__DEMO_MODE__ = true;
  }

  static disableDemoMode(): void {
    global.__DEMO_MODE__ = false;
  }

  static getDashboardData(): GetDashboardDataQuery {
    return DEMO_DASHBOARD_DATA;
  }

  static getDockerData(): GetDockerContainersQuery {
    return DEMO_DOCKER_DATA;
  }

  static getVMsData(): GetVmsQuery {
    return DEMO_VMS_DATA;
  }

  static getNotificationsData(): DemoNotificationsData {
    return DEMO_NOTIFICATIONS_DATA;
  }
}

// Extend global namespace for TypeScript
declare global {
  var __DEMO_MODE__: boolean | undefined;
}

